Added Gentoo Install Script for OpenRC based systems
1337-server/automatic-ripping-machine pull request #96
Opened 2021-09-03 20:06 UTC by mneimeyer

With the caveat that Gentoo is a multi-headed beastie resulting from being an eminently configurable and rolling distro I offer this as at least a starting point. In other words, it works for me. :)

I personally do not run systemd but I assume this could be expanded by adapting some portions of the Debian or Ubuntu install scripts. I also have not, and probably won't, develop a quiet version. Especially because of the variability of the JRE. Also, I like my scripts "loud".

Long run, it would probably be best to try and adapt this into an ebuild so that it can be more "Portage aware". I balked at that because I don't know of a way to parse the requirements.txt into DEPENDS lines "on the fly". Especially not before the git repository is cloned.

2021-09-06 00:23 UTC, 1337-server requested changes
Changes look great, but some small changes are needed.

2021-09-06 00:23 UTC, 1337-server commented on arm/ripper/main.py
> +        if job.disctype == "dvd":
Would be best to add a check for the `JACKET_P` folder before continuing, as this would save mounting and unmounting. The disc at this point should still be mounted, so there should be no need to call the mount/umount as arm already deals with this.

2021-09-06 00:23 UTC, 1337-server commented on arm/ripper/main.py
> +                logging.info(f"File: poster.png already exists.  Not moving.")
`logging.info(f"File: poster.png already exists. Not moving.")`

Needs changed to remove the f before the string.

`logging.info("File: poster.png already exists. Not moving.")`

The f"" lets python know that the string is an fstring and that variables/extra processing will be required. But this isn't needed as the string has no variables.

2021-09-06 00:23 UTC, 1337-server commented on arm/ripper/main.py
> +                os.system('ffmpeg -i "'+job.mountpoint+'/JACKET_P/J00___6L.MP2" "'+hb_out_path+'/poster.png"')
This might fail on some systems, as ffmpeg isn't installed in the ubuntu version. Although I could be wrong, as it has been a while since I fully reset my ubuntu VM.

2021-09-06 15:02 UTC, mneimeyer commented on arm/ripper/main.py
> +        if job.disctype == "dvd":
I tried to sort out the logic of when the disk was mounted/unmounted and apparently failed. :) I'd love help with that part.

2021-09-06 15:04 UTC, mneimeyer commented on arm/ripper/main.py
> +                os.system('ffmpeg -i "'+job.mountpoint+'/JACKET_P/J00___6L.MP2" "'+hb_out_path+'/poster.png"')
I had ditched the Ubuntu VM I tossed together when I sanity checked the Ubuntu install script. I downloaded two Ubuntu VMs from osboxes.org (20.04 and 21.04) and neither had ffmpeg.

I'll hide the poster rip behind a config option and maybe see if I can auto-detect if ffmpeg is available and auto-set it.

2021-09-09 19:55 UTC, 1337-server commented on arm/ripper/main.py
> +                os.system('ffmpeg -i "'+job.mountpoint+'/JACKET_P/J00___6L.MP2" "'+hb_out_path+'/poster.png"')
That sounds fine.

2021-09-09 19:57 UTC, 1337-server commented on arm/ripper/main.py
> +        if job.disctype == "dvd":
That seems odd, but if you need to mount it, that shouldn't affect anything. But the check for the existence of the JACKET_P folder would still need added.

2021-09-15 22:09 UTC, 1337-server commented
Are you ok to do the changes suggested by code climate ? If not, I can merge and then fix the issues.

Just let me know.

2021-09-18 14:31 UTC, mneimeyer commented
> Just let me know.

Life... Ugh... Yes I'm going to try and finish up this stuff this weekend if I can. Thx

2021-09-26 20:47 UTC, mneimeyer commented
I believe I've resolved the outstanding requested changes with the exception of the mount/remounting for the poster. I tried tracing the program flow again and I'm still not seeing what I think I should. My apologies.

2021-09-27 22:56 UTC, merged